# Generated by Django 5.2.7 on 2025-11-03 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_date', models.DateField(blank=True, help_text="Client's preferred date for the post", null=True)),
                ('request_details', models.TextField(help_text='Details and ideas for the post')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VIEWED', 'Viewed by Admin'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_requests', to='users.clientprofile')),
            ],
        ),
    ]
