# Generated by Django 5.2.3 on 2025-11-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_from_request',
            field=models.ForeignKey(blank=True, help_text='The client request this post was created from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to='posts.postrequest'),
        ),
    ]
